add logs to git tag step

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -48,9 +48,10 @@ jobs:
           git config user.email noreply@ngrok.com
           tag="${{inputs.crate}}-v${version}"
           echo "Version ${version}, tag ${tag}"
-          if git rev-parse "refs/tags/$tag" >/dev/null 2>&1; then
+          echo "Current working directory: $(pwd)"
+          rev_parse_output=$(git rev-parse "refs/tags/$tag" 2>&1)
+          if [ $? -eq 0 ]; then
             echo "Tag $tag already exists, skipping tag creation."
           else
-            git tag -a -m "Version ${version}" $tag
-            git push --tags
+            echo "Error from git rev-parse: $rev_parse_output"
           fi
